services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${PROJECT_NAME}
      MARIADB_USER: ${DB_SLAVE_USER_NAME}
      MARIADB_PASSWORD: ${DB_SLAVE_USER_PASSWORD}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ~/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_SLAVE_USER_NAME} -p${DB_SLAVE_USER_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-container
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - app-network

  app:
    image: $DOCKER_HUB_USER_NAME/${PROJECT_NAME}:${PROJECT_VERSION}
    container_name: ${PROJECT_NAME}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_VERSION: ${PROJECT_VERSION}
      SPRING_DATASOURCE_MASTER_URL: jdbc:mariadb://ddip-db.c1smcu2wa2ue.us-east-2.rds.amazonaws.com:3306/${PROJECT_NAME}
      SPRING_DATASOURCE_MASTER_USERNAME: ${DB_MASTER_USER_NAME}
      SPRING_DATASOURCE_MASTER_PASSWORD: ${DB_MASTER_USER_PASSWORD}
      SPRING_DATASOURCE_SLAVE_URL: jdbc:mariadb://mariadb-container:3306/${PROJECT_NAME}
      SPRING_DATASOURCE_SLAVE_USERNAME: ${DB_SLAVE_USER_NAME}
      SPRING_DATASOURCE_SLAVE_PASSWORD: ${DB_SLAVE_USER_PASSWORD}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      NAVER_API_URL: ${NAVER_API_URL}
      NAVER_API_KEY_ID: ${NAVER_API_KEY_ID}
      NAVER_API_KEY_SECRET: ${NAVER_API_KEY_SECRET}
      DDIP_S3_ACCESS_KEY: ${DDIP_S3_ACCESS_KEY}
      DDIP_S3_SECRET_KEY: ${DDIP_S3_SECRET_KEY}
      DDIP_S3_BUCKET_NAME: ${DDIP_S3_BUCKET_NAME}
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - /home/ubuntu/keystore.p12:/app/keystore.p12

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
