#server:
#  url: ${DDIP_IP}
#  port: 443
#  ssl:
#    key-store: file:/app/keystore.p12
#    key-store-password: ${SSL_KEY_STORE_PASSWORD}
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  application:
    name: ddip
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /
      suffix: .html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: three
    password: four
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3307/ddip?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
  #    datasource:
  #      master:
  #        driver-class-name: org.mariadb.jdbc.Driver
  #        jdbc-url: jdbc:mariadb://${PROJECT_NAME}-db.c12qq8qq0tns.ap-northeast-2.rds.amazonaws.com:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
  #        username: ${DB_MASTER_USER_NAME}
  #        password: ${DB_MASTER_USER_PASSWORD}
  #      slave:
  #        driver-class-name: org.mariadb.jdbc.Driver
  #        jdbc-url: jdbc:mariadb://mariadb-container:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
  #        username: ${DB_SLAVE_USER_NAME}
  #        password: ${DB_SLAVE_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true
    show-sql: true
    database: mysql
    address:
      api-key: ${API_KEY}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  redis:
    host: redis-container
    port: 6379
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis
    timeout: 1800s
  jwt:
    secret: ${JWT_SECRET_KEY}
  config:
    import: classpath:/application-local.yml
  profiles:
    active: local
logging:
  config: classpath:logback-spring.xml
naver:
  api:
    url: ${NAVER_API_URL}
    key:
      id: ${NAVER_API_KEY_ID}
      secret: ${NAVER_API_KEY_SECRET}
cloud:
  aws:
    credentials:
      access-key: ${DDIP_S3_ACCESS_KEY}
      secret-key: ${DDIP_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket-name: ${DDIP_S3_BUCKET_NAME}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
image:
  upload:
    dir: ~/